name: A workflow
on: push
jobs:
  build:
    name: Action Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Chris"
